const Images=[
    {
        id:1,
        product:'lotion',
        location:'/assets/lotion.svg'
    },
    {
        id:2,
        product:'shampoo',
        location:'/assets/shampoo.svg'
    },
    {
        id:3,
        product:'Powder',
        location:'/assets/Powder.svg'
    },
    {
        id:4,
        product:'milk',
        location:'/assets/milk.svg'
    },
    {
        id:5,
        product:'apple',
        location:'/assets/apple.svg'
    },
    {
        id:6,
        product:'cosmetics',
        location:'/assets/cosmetics.svg'
    },
    {
        id:7,
        product:'Bicycle',
        location:'/assets/Bicycle.svg'
    },
    {
        id:8,
        product:'scale',
        location:'/assets/scale.svg'
    },
    {
        id:9,
        product:'eraser',
        location:'/assets/eraser.svg'
    }
    
]

export default Images;